In [17]:
# Test del chi-quadro di indipendenza

In [1]:
import numpy as np
from scipy.stats import chi2

In [2]:
X = np.array([[44., 10.],[81., 35]])

In [3]:
n = 170

In [4]:
# Probabilità empiriche di trattamento
p = np.array([54., 116.])/n
display('Probabilità empirica di trattamento', p)

'Probabilità empirica di trattamento'

array([0.31764706, 0.68235294])

In [5]:
# Probabilità empiriche di guarigione
q = np.array([125., 45.])/n
display('Probabilità empirica di guarigione', p)

'Probabilità empirica di guarigione'

array([0.31764706, 0.68235294])

In [6]:
# Probabilità congiunta empirica
pi = X/n
display(pi)

array([[0.25882353, 0.05882353],
       [0.47647059, 0.20588235]])

In [24]:
T = 0.
for h in range(2):
    for k in range(2):
        T = T + (p[h]*q[k]-pi[h][k])**2./pi[h][k]
T = n*T
display(T)

3.0175117739708286

In [26]:
alpha = 0.05
CHI = chi2.ppf(1.-alpha,(2-1)*(2-1))
display(CHI)

3.841458820694124

In [ ]:
# Non si può rigettare l'ipotesi nulla.
# Questo fa sospettare che ci sia stato un effetto placebo.